### ISSUE TITLE
Jackett downloads do not work

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#51] opened 2018-01-11 08:58 UTC
When trying to download search result from Jackett, it tries to use an address from 127.0.0.1, which obviously will not work when accessing it via the public IP.

**Comment by liaralabs** [comment] 2018-01-11 19:32
This should be fixed now:
`box update` and then `box upgrade nginx` to update your configs :slightly_smiling_face:

**Comment by liaralabs** [comment] 2018-01-11 21:00
I accidentally did my testing with remote access enabled; thus the fix isn't working as intended. Changing Host from $proxy_host to $host has removed external access to jackett.

This appears to be a larger issue with mono in general, as it is Sonarr, Radarr and Jackett who all require $proxy_host when external access is disabled. I have opened a ticket with Jackett, and hope that something can be sorted.

Until then, there's not much that can be done on this issue.

https://github.com/Jackett/Jackett/issues/2404

**Comment by liaralabs** [comment] 2018-01-11 21:06
Alternatively, if upstream cannot fix, I will look into forcing an admin password and leaving remote access enabled. You'll potentially have to enter your password twice; however, it will work around the constraints if there is no alternative.

**Comment by d2dyno** [comment] 2018-01-11 22:01
Hmm, that is troubling. Thanks for the detective work, to my lazy issue xD Kaso from the Jackett team, is pretty good IIRC, so hopefully, they can get this sorted out.

**Comment by d2dyno** [comment] 2018-03-04 05:13
@drew7721 that sounds like a different issue, that is not pertinent to this issue :smile:

**Comment by liaralabs** [comment] 2018-08-18 20:12
This has been fixed in the most recent version of jackett.

**Closed by liaralabs** 2018-08-18 20:12 UTC
