### ISSUE TITLE
1.1 Libtorrent branch RC_1_1 not Installing

### ISSUE THREAD

**Issue by adir6** [liaralabs/swizzin#402] opened 2020-09-15 10:37 UTC
## Bug description
I have been trying to install Deluge 1.3.15 with Libtorrent 1.1 RC (which would pickup the latest version) but upon doing that, it doesn't install the intended version but just keeps the older version which was previously installed.

## Reproduction steps
1. Uninstall Current Version of Deluge.
2. Re-install Deluge 1.3.15 with Libtorrent 1.1RC Selected.
3. It will throw the error: https://i.imgur.com/PgJ8Cia.png

![sx-15-September-20-7255](https://user-images.githubusercontent.com/9323342/93203277-c06dae00-f771-11ea-8492-0e38053cb1bc.png)

**Note: I tried to install new server with swizzin. The same error comes with the initial setup as well.**

![sx-15-September-20-7256](https://user-images.githubusercontent.com/9323342/93203225-acc24780-f771-11ea-860c-707c8eaf9050.png)

I could be wrong but I went to the file-directory as shown in the error. The file name seems to be different from what swizzin says in error.

![sx-15-September-20-7257](https://user-images.githubusercontent.com/9323342/93203677-76d19300-f772-11ea-9e00-93d42177d0ec.png)

## Installed applications through swizzin
Nginx, ffmpeg, panel, rutorrent, deluge, filebrowser, autodl-irrsi

## Expected behavior
It should have installed the Libtorrent 1.1.14 as that's the latest version in 1.1 series.

## Server Info
 - OS: Debian 10.5
 - Image Source: installimage from Hetzner

## Is Swizzin up to date?
It says I am on master branch and it's upto date.

Head: 687c813 

## Additional context

Install Logs: http://termbin.com/fwu6 (New) | https://pastebin.com/raw/zV4MNkVg (Old Installation)
Swizzin Logs: Missing (If you want, I can re-install)
Nginx Error Logs: Missing
journalctl -xe: https://i.imgur.com/ZMR9cEv.png

**Comment by liaralabs** [comment] 2020-09-15 16:05
Please supply the logs requested in the additional context section. Without detailed logs, there is no indication of what might be going wrong.

**Comment by adir6** [comment] 2020-09-15 16:18
> Please supply the logs requested in the additional context section. Without detailed logs, there is no indication of what might be going wrong.

Okay. I'm updating that in few minutes and I'll tag or let you know. Thanks

**Comment by adir6** [comment] 2020-09-15 16:42
Hi @liaralabs, I have added the logs, strange but Swizzin Log is missing.

**Comment by liaralabs** [comment] 2020-09-15 17:03
The log output is truncated and it does not seem to be complete. If you are having troubles getting the full logs up to the service you can try dumping the log directly to the paste service termbin:

```
cat /root/logs/install.log | nc termbin.com 9999
```

swizzin.log is the log file that is used after the main installation, so if you have only done the base install this will not yet exist.

**Comment by adir6** [comment] 2020-09-15 17:17
> The log output is truncated and it does not seem to be complete. If you are having troubles getting the full logs up to the service you can try dumping the log directly to the paste service termbin:
> 
> ```
> cat /root/logs/install.log | nc termbin.com 9999
> ```
> 
> swizzin.log is the log file that is used after the main installation, so if you have only done the base install this will not yet exist.

Yes, It's the base installation only. I just did new installation as I thought swizzin log is missing for some reason.

New Installation Log Link: termin.com/fwu6

**Comment by adir6** [comment] 2020-09-15 17:20
> The log output is truncated and it does not seem to be complete. If you are having troubles getting the full logs up to the service you can try dumping the log directly to the paste service termbin:
> 
> ```
> cat /root/logs/install.log | nc termbin.com 9999
> ```
> 
> swizzin.log is the log file that is used after the main installation, so if you have only done the base install this will not yet exist.

Thanks for the reply. Yes, It's the base installation only. I just did new installation as I thought swizzin log is missing for some reason.

New Installation Log Link: http://termbin.com/fwu6

**Comment by liaralabs** [comment] 2020-09-15 17:32
It looks like I've just discovered a bug with the panel install clobbering the install log, so unfortunately it looks like you have sent over the full log (though I've just committed to fix this in the future).

Can you please try the following:

```
box remove deluge
box install deluge
```

Now, `/root/logs/swizzin.log` should contain the output related to the deluge install/compile and only that.

That said, I cannot reproduce your issue on a freshly installed Debian 10 image even using Hetzner.

**Comment by adir6** [comment] 2020-09-15 17:38
> It looks like I've just discovered a bug with the panel install clobbering the install log, so unfortunately it looks like you have sent over the full log (though I've just committed to fix this in the future).
> 
> Can you please try the following:
> 
> ```
> box remove deluge
> box install deluge
> ```
> 
> Now, `/root/logs/swizzin.log` should contain the output related to the deluge install/compile and only that.
> 
> That said, I cannot reproduce your issue on a freshly installed Debian 10 image even using Hetzner.

Here is the swizzin.log as you have asked for: http://termbin.com/cdl1

When this building/binding is happening for the python, libtorrent, deluge, CPU goes as high as 100% constantly: https://i.imgur.com/e4ryKF6.png

Well, I am using Hetzner with installimage command to install the Ubuntu 10.5 Minimal. I am doing nothing custom or anything which should make our case different from each other unless you can tell me certain steps to do?

I'm doing everything as mentioned on the docs.

**Comment by adir6** [comment] 2020-09-15 17:59
> > It looks like I've just discovered a bug with the panel install clobbering the install log, so unfortunately it looks like you have sent over the full log (though I've just committed to fix this in the future).
> > Can you please try the following:
> > ```
> > box remove deluge
> > box install deluge
> > ```
> > 
> > 
> > Now, `/root/logs/swizzin.log` should contain the output related to the deluge install/compile and only that.
> > That said, I cannot reproduce your issue on a freshly installed Debian 10 image even using Hetzner.
> 
> Here is the swizzin.log as you have asked for: http://termbin.com/cdl1
> 
> When this building/binding is happening for the python, libtorrent, deluge, CPU goes as high as 100% constantly: https://i.imgur.com/e4ryKF6.png
> 
> Well, I am using Hetzner with `installimage` command to install the Debian 10.5. I am doing nothing custom or anything which should make our case different from each other unless you can tell me certain steps to do?
> 
> I'm doing everything as mentioned on the docs.

Please let me know if that is fine or you need anything else?

**Comment by liaralabs** [comment] 2020-09-15 18:15
I have just pushed a commit which should fix the behaviour you are experiencing.

Can you please test and report back? (Either `box update` and reinstall deluge or a fresh installation)

**Comment by adir6** [comment] 2020-09-15 18:16
> I have just pushed a commit which should fix the behaviour you are experiencing.
> 
> Can you please test and report back? (Either `box update` and reinstall deluge or a fresh installation)

Whichever you think is the best option, I will go with it. Please call it!

**Comment by adir6** [comment] 2020-09-15 19:17
Hi, I did the fresh installation. But if you could check the logs: http://termbin.com/ps472

Also, Please do check if your log is logging everything now?
> It looks like I've just discovered a bug with the panel install clobbering the install log, so unfortunately it looks like you have sent over the full log (though I've just committed to fix this in the future).

**Comment by liaralabs** [comment] 2020-09-15 21:01
Logging looks good :+1: 

Looks like everything is installing correctly now, so I will close this issue. If the issue persists, please re-open

**Closed by liaralabs** 2020-09-15 21:01 UTC
Labels: needs info

**Comment by adir6** [comment] 2020-09-15 21:50
Thanks for the help Liara :+1:
