### ISSUE TITLE
Script hangs on jackett installation

### ISSUE THREAD

**Issue by herrwusel** [liaralabs/swizzin#156] opened 2018-10-24 13:07 UTC
OS: Ubuntu 18.04
When script comes to jackett installation it never finish.

**Comment by 2wenty2wo** [comment] 2019-02-02 05:09
OS: Ubuntu 16.04
I'm also having this problem.

**Comment by redac** [comment] 2019-04-07 09:12
OS: Ubuntu 18.04
Same here, even left it for a whole night running.

**Comment by liaralabs** [comment] 2019-04-23 22:16
I still can't replicate this one on a fresh installation.

If your server is still acting up and does it on a fresh install, can you send me over your install.log in /root/logs/install.log?

Otherwise, if it's freezing on a current installation

```
bash -x /etc/swizzin/scripts/install/jackett.sh
```

Will output the commands being run as they're happening and should allow you to see exactly which command the installer is stuck on

**Comment by sumoo13** [comment] 2019-04-25 18:02
i have the same problem
with your command line, the script hangs with 
`+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
+ '[' '!' -f /home/jooker/.config/Jackett/ServerConfig.json ']'
+ sleep 2
`

**Comment by AoNoEzreal** [comment] 2019-06-15 18:11
i don't know if is linked but the jackett archive that is downloaded by the script Jackett.sh does not contain JacketConsole.exe 

without it Jackett can't run and thus can't create the ServerConfig.json

**Comment by liaralabs** [comment] 2019-06-15 18:25
Jackett no longer relies on the mono for the version we are pushing here, thus exes are no longer used for the installation of Jackett.

I understand that the waiting line is causing issues for some; however, I'm not able to reproduce this. The reason why the installer is in a sleep loop is because the next steps rely on the Jackett server config being present to continue; otherwise the setup for the nginx proxy will be incorrect.

If Jackett isn't creating the ServerConfig.json, it's likely not starting properly, which is indicative of a different issue. I'd be curious to know if folks are actually still experiencing this issue after moving to the native binaries.

**Comment by AoNoEzreal** [comment] 2019-06-15 18:51
yeah i figured out as much after i posted my comment and yes the issue is that jackett is not starting when using systemctl start jackett@$username 
i'm currently experiencing it on my debian 8 server and it's been a present issue through 3 complete reinstallations of my server

**Comment by AoNoEzreal** [comment] 2019-06-15 19:22
i got it up and running after changing the ExecStart command from 
`ExecStart=/home/%I/Jackett/jackett --NoRestart` 
to
`ExecStart=/home/seedbox/Jackett/jackett --NoRestart`

which is my username, i don't know why %I did not work

**Comment by liaralabs** [comment] 2019-06-15 20:21
The problem you're facing is likely a different one than the folks who are running Xenial or Bionic.

The reason why the command won't start Jackett for you is because the version of systemd shipped in Debian Jessie is v215 and specifier expansion in the first part of the execstart line wasn't supported until v224.

You would only have started to experience this issue following the commit to remove mono from Jackett because the ExecStart line no longer calls `/usr/bin/mono` before specifying where to find the jackett exe.

Unfortunately backports for systemd are no longer an option because they are no longer being maintained for Jessie. It may be a workaround to change 

```
 ExecStart=/home/%I/Jackett/jackett --NoRestart
```
to
```
 ExecStart=/bin/sh -c "/home/%I/Jackett/jackett --NoRestart"
```
In order to retain the  multi-user aspect of Jackett. This is how the nzbget binary is called. I'm willing to add a distro specific command for Jessie if that helps the service start; however, this still likely doesn't fix the issue of the ServerConfig not being created under Ubuntu platforms.

**Comment by liaralabs** [comment] 2019-07-01 18:12
The infinite loop has been fixed; however, I suspect this will not fix issues where Jackett isn't actually starting on Ubuntu 18.04.

If you're still having issues with jackett starting, please open a new issue rather than continuing this thread as the infinite loop has been considered fixed.

**Closed by liaralabs** 2019-07-01 18:12 UTC
