### ISSUE TITLE
Pyload and Letsencrypt

### ISSUE THREAD

**Issue by pirate42** [liaralabs/swizzin#159] opened 2018-10-26 20:21 UTC
Hello,

On a "fresh" install of Ubuntu 18.04.1 LTS, there is some errors:

Here is the CMD MSG:

"
Do you want to apply this certificate to your swizzin default conf? (y/n) y
Is your DNS managed by CloudFlare? (y/n) y
Does the record for this subdomain already exist? (y/n) y
Enter CF API key
(Hiden *** Hiden)
CF Email
(Hiden *** Hiden)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185    0   185    0     0    548      0 --:--:-- --:--:-- --:--:--   547
API CALL FAILED. DUMPING RESULTS:
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
Installing netdata
Installing nzbget
Installing pyload
Installing any additional dependencies needed for pyLoad ...
Setting up python package management system in /home/pirate/.pip ...
Installing pyLoad packages ...
Grabbing latest stable pyLoad repository ...
Building pyLoad systemd template ...
Adjusting permissions ...
#### and do not alter the default port (8000) ####
Traceback (most recent call last):
  File "/home/pirate/.pyload/pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/home/pirate/.pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/home/pirate/.pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/home/pirate/.pyload/module/network/HTTPRequest.py", line 21, in <module>
    import pycurl
ImportError: No module named pycurl
sed: can't read /home/pirate/.pyload/pyload.conf: No such file or directory
sed: can't read /home/pirate/.pyload/pyload.conf: No such file or directory
Enabling and starting pyLoad services ...
pyLoad Install Complete!
"

Any clue of what the trouble might be ?

Thanks for your help and contribution ;)

**Comment by liaralabs** [comment] 2018-10-30 21:17
This pyload issue is likely a duplicate of #122 -- please read and search to see if the comments there help the problem. If not, contribute further there. I have been very busy lately and haven't had lots of time to commit fixes to the repo.

As for LE:

```
Invalid format for X-Auth-Key header
```

Are you sure your CF Key is correct? There are no issues with the way the API is being called. The error leads me to believe you input an invalid API key.

**Closed by liaralabs** 2018-10-30 21:17 UTC

**Comment by bjeanes** [comment] 2020-10-31 23:33
I have this same CF API key error and my key is definitely valid, as I am using it in another LetsEncrypt setup for the same domain and it continues to work fine.
