### ISSUE TITLE
The rtorrent cannot run

### ISSUE THREAD

**Issue by Csedge** [liaralabs/swizzin#195] opened 2019-03-25 10:13 UTC
Try to reinstall again, still happen problem. The output from systemctl is below
Ubuntu 18.04
root@ubuntu:/home/seedbox# sudo systemctl status rtorrent@seedbox
● rtorrent@seedbox.service - rTorrent
   Loaded: loaded (/etc/systemd/system/rtorrent@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-03-25 10:02:20 UTC; 8min ago
 Main PID: 28341 (code=exited, status=0/SUCCESS)

Mar 25 10:02:19 ubuntu systemd[1]: Starting rTorrent...
Mar 25 10:02:19 ubuntu systemd[1]: Started rTorrent.
Mar 25 10:02:20 ubuntu screen[28390]: No screen session found.
Mar 25 10:02:20 ubuntu systemd[1]: rtorrent@seedbox.service: Control process exited, code=exited status=1
Mar 25 10:02:20 ubuntu systemd[1]: rtorrent@seedbox.service: Failed with result 'exit-code'.

**Comment by liaralabs** [comment] 2019-03-25 20:13
Duplicate of #191

**Closed by liaralabs** 2019-03-25 20:13 UTC
