### ISSUE TITLE
Jellyfin installation: tar issues

### ISSUE THREAD

**Issue by Wyall** [liaralabs/swizzin#278] opened 2020-04-07 12:12 UTC
**Describe the bug**
On sudo box install jellyfin I recieve several tar issues. It says later the installation has completed and I can access the Jellyfin interface. Maybe this is still interesting though. I tried this two times. 
I had installed jellyfin previously on my own but removed it in advance.

**To Reproduce**
Install jellyfin with box install jellyfin

**Server Info (please complete the following information):**
 - OS: Ubuntu 18.04.04

**Additional context**
```
sudo box install jellyfin
Installing jellyfin
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now

The Jellyfin installation has completed

Jellyfin is now available in the panel

Please visit https://ip/jellyfin
```

**Comment by userdocs** [comment] 2020-04-07 13:23
I am not able to replicate your issue.

**Comment by Wyall** [comment] 2020-04-07 13:42
I also guess you would have noticed something like this :) 
Can I do anything to get you more information, should we wait if somebody else sees this or just close it?

**Comment by userdocs** [comment] 2020-04-07 15:20
It might just be github being wierd. You can try this.

Here is the relevant line of the installation script.

https://github.com/liaralabs/swizzin/blob/master/scripts/install/jellyfin.sh#L55

You may have hit github api rate limiting for your IP.

You can check with this command

~~~
curl -si https://api.github.com/users/octocat | grep 'X-Ratelimit'
~~~

If your `X-Ratelimit-Remaining` is not `0` then try this command in your ssh session directly.

~~~
curl -s https://api.github.com/repos/jellyfin/jellyfin/releases/latest | grep -Po 'ht(.*)linux-amd64(.*)gz'
~~~

**Comment by Wyall** [comment] 2020-04-07 15:51
I removed and installed again, just to be sure. Same error still.
But in the end jellyfin works, I can access the setup page in my browser. So maybe it's something unimportant.

Your first command gives 
```
wyall@OP:~$ curl -si https://api.github.com/users/octocat | grep 'X-Ratelimit'
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 58
X-Ratelimit-Reset: 1586277858
```
The second then
```
wyall@OP:~$ curl -s https://api.github.com/repos/jellyfin/jellyfin/releases/latest | grep -Po 'ht(.*)linux-amd64(.*)gz'
https://github.com/jellyfin/jellyfin/releases/download/v10.5.3/jellyfin_10.5.3_linux-amd64.tar.gz
```

**Comment by userdocs** [comment] 2020-04-07 15:59
then this might be related to ffmpeg.

https://github.com/liaralabs/swizzin/blob/master/scripts/install/jellyfin.sh#L59

Can you please check to see if it got extracted to `/opt/ffpmeg`

**Comment by Wyall** [comment] 2020-04-07 16:16
It seems like something went wrong there:
```
ls -lah /opt/ffmpeg/
total 86M
drwx------  2 wyall wyall 4.0K Apr  7 17:44 .
drwxr-xr-x 10 root  root  4.0K Apr  7 17:44 ..
-rwx------  1 wyall wyall    0 Apr  7 17:44 ffmpeg.tar.xz
-rwx------  1 wyall wyall  86M Apr  7 17:44 jellyfin.tar.gz
```

**Comment by userdocs** [comment] 2020-04-10 00:09
I can't help based on this information as I cannot see how those files ended up there whilst also not being able to reproduce this issue.

**Comment by liaralabs** [comment] 2020-04-10 00:14
If you're still having this issue, you could try removing jellyfin and then
reinstalling from shell with debug enabled:

`bash -x /etc/swizzin/scripts/install/jellyfin.sh`

This will cause the interpreter to report what's going on at each and every
step of the script. It may be something as simple as the ffmpeg url not
resolving/redirecting properly, resulting in an empty file.

**Comment by Lukylix** [comment] 2020-04-10 02:34
The problematic part : 
```
+ wget -qO /tmp/jellyfin/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
++ tar tf /tmp/jellyfin/ffmpeg.tar.xz
++ head -1
++ cut -f1 -d/
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
+ ffmpeg_dir_name=
+ tar xf /tmp/jellyfin/ffmpeg.tar.xz -C /tmp/jellyfin
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
+ rm -rf /tmp/jellyfin//manpages /tmp/jellyfin//model /tmp/jellyfin//GPLv3.txt /tmp/jellyfin//readme.txt
```

**Comment by liaralabs** [comment] 2020-04-10 07:07
If you run this manually, does it result in a tar file or output an error?

```
mkdir /tmp/jellyfin
wget -qO /tmp/jellyfin/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
```

**Comment by userdocs** [comment] 2020-04-10 10:05
I think we should look at debugging URL itself and the remove the `-q` from the command. There is no obvious problem downloading this URL so there must be a reason he gets a null download. This seems to be the specific problem.

`-d` debug and `-v` verbose might help.

~~~
mkdir /tmp/jellyfin
wget -dvO /tmp/jellyfin/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
~~~

What i can see so far is like this:

**1:** ffmpeg fails to download for an unknown reason.
**2:** the tar command to get the directory name fails as a result so the value of [ffmpeg_dir_name](https://github.com/liaralabs/swizzin/blob/master/scripts/install/jellyfin.sh#L62) is null
**3:** the directory created from previous command is a null value so no directory is made.
**4:** since the value is null the copy command copies form a directory above what it should.
**5:* The wrong files are copied to `/opt/ffmpeg` and we have no `ffmpeg` binary.

It is a domino effect from the first step of the issue.

**Comment by Wyall** [comment] 2020-04-10 14:56
I removed the -q
The URL did not resolve.
```
wget -O /tmp/jellyfin/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-
static.tar.xz
--2020-04-10 16:30:56--  https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘johnvansickle.com’
```
I don't know if this is the correct way but I added 8.8.8.8 in /etc/resolvconf/resolv.conf.d/head and afterwards it works. What a stupid issue :-\

**Comment by liaralabs** [comment] 2020-04-29 00:08
DNS resolution is outside the scope of what swizzin does. If anyone faces this in the future, the work around here is to ensure you're using a resolver such as CloudFlare or Google in your `/etc/resolv.conf`

**Closed by liaralabs** 2020-04-29 00:08 UTC
