### ISSUE TITLE
autodl-irssi

### ISSUE THREAD

**Issue by heathwalton** [liaralabs/swizzin#32] opened 2017-10-21 18:08 UTC
autodl-irssi is not working and I am receiving the follow error in the rutorrent log section:

"Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Error getting files listing: Error: Invalid port ()! Initialize port in conf.php"

 I have tried installing swizzin on fresh installs of debian stretch and ubuntu 16.04 but keep getting this error. What should I check? Is this a permissions issue?

**Comment by liaralabs** [comment] 2017-10-21 20:21
The autodl rutorrent plugin was recently updated with a new ZeroConf option. Unfortunately, this has had the effect of breaking our current implementation whereby autodl configuration parameters are stored in ~/.autodl/autodl2.cfg.

I will not be committing any changes at this time until the issue [here](https://github.com/autodl-community/autodl-rutorrent/issues/37) receives attention from the dev.

A current work around to the issue is to simply issue the command as your user (not as root):
`cat ~/.autodl/autodl2.cfg >> ~/.autodl/autodl.cfg`

**Comment by weaselBuddha** [comment] 2017-10-22 12:07
Our temporary fix (I'm presuming a full fix will come from the autodl folks), is to comment out the zero config invocation:

`
//try {
//      $config = attemptZeroConfig();
        //$autodlPort = $config['gui-server-port'];
        //$autodlPassword = $config['gui-server-password'];
//} catch (Exception $e) {
        eval(getPluginConf('autodl-irssi'));
//}
`

Hope that helps

**Comment by liaralabs** [comment] 2017-10-22 17:43
I do agree that autodl2.cfg is indeed useful for portability. Perhaps a slightly more elegant solution would be to just reset to the commit just before the zeroconf changes, this allows the plugin folder to retain git pull functionality in swizzin, rather than needing to stash the commented out changes to the repo before being able to pull again:

```
cd /srv/rutorrent/plugins/autodl-irssi
git reset --hard 17c689fa82e8ca1f1a55cd935ed41e2bf98f8237
```

**Comment by manwithnoname** [comment] 2017-11-08 11:30
Does this [commit](https://github.com/autodl-community/autodl-rutorrent/commit/de602e7dc6fee8a39516646ef6bab7e3c4318929) from 5 days ago solve this?

**Comment by liaralabs** [comment] 2017-11-08 18:21
This should be fixed now, but I haven't had a chance to test it

**Closed** 2017-11-13 21:22 UTC
