### ISSUE TITLE
Deluge download 403 forbidden error

### ISSUE THREAD

**Issue by mrlongshen** [liaralabs/swizzin#78] opened 2018-03-20 14:10 UTC
I got 403 Forbidden on deluge download, after install letsencrypt. why ?

**Comment by liaralabs** [comment] 2018-07-01 19:54
Cannot reproduce and there have been no further updates, so I am closing this issue. If you can provide more info, please feel free to re-open.

**Closed by liaralabs** 2018-07-01 19:54 UTC

**Comment by sahrechiiz** [comment] 2018-09-13 14:07
Hi, i'm getting this error too.

Panel and deluge web opens correctly. The deluge.downloads shows 403.

I've tried install the repo version and the stable version of deluge. same thing. (i know the problem can't be there. just in case.😝）

I have 2 servers. The other one installed deluge using swizzin last month. Didn't have a problem. I assume the changing after that broke something?

here are the logs if it helps.

[logs.zip](https://github.com/liaralabs/swizzin/files/2379610/logs.zip)

**Comment by forsomefun2** [comment] 2018-10-21 04:09
I found a fix for at least one of these issues
not sure about the first guy because he never gave any logs

The fix is to 
setfacl -R -m u:www-data:rwx /home/User name/

I don't know why but it needs to be the home directory and not the specific folder. 
If setfacl doesn't work I think you need to install acl or acltools, but I think that a default program.


Findings

I think maybe you should look into this error again if possible

I actually looked at the last guys error log, and I notice this line 
`2018/09/13 11:02:08 [error] 6159#6159: *2 "/home/xxx/torrents/deluge/index.html" is forbidden (13: Permission denied), client: x.x.x.x, server: box.xxx.cloud, request: "GET /deluge.downloads/ HTTP/1.1", host: "box.xxx.cloud"`

Actually on mine I also get 
`2018/10/21 05:49:46 [error] 18621#18621: *879 open() "/home/snickerpop/torrents/deluge" failed (13: Permission denied), client: 107.4.175.66, server: snickerpop.com, request: "GET /Downloads_Deluge HTTP/1.1", host: "snickerpop.com", referrer: "https://snickerpop.com/"
`

This is with a clean install
box uninstall nginx panel flood rtorrent rutorrent 
letsencrypt is not install
certbot was setup but is no longer install after box uninstall nginx



So from that it seems that the issue has to do with how permissions are 

I think the issue is as described here
https://stackoverflow.com/questions/6795350/nginx-403-forbidden-for-all-files
