### ISSUE TITLE
Syncthing Install Fails 

### ISSUE THREAD

**Issue by Loomaanaatii** [liaralabs/swizzin#19] opened 2017-08-29 03:18 UTC
NGINX 502 Bad Gateway after install, how would I fix this?

**Comment by liaralabs** [comment] 2017-08-29 05:43
Syncthing isn't reverse proxied. You need to access it directly from IP:8888/web if my memory serves me correctly.

**Comment by Loomaanaatii** [comment] 2017-08-29 06:09
Okay because in the quick box UI it shows syncthing (offline).

**Comment by liaralabs** [comment] 2017-08-29 19:58
In my tests, syncthing has been installing reliably.

Try to restart syncthing (`systemctl restart syncthing`)

If syncthing is still not running after that, then I need debug information such as
`systemctl status syncthing`
and
`journalctl -u syncthing.service`

**Comment by liaralabs** [comment] 2017-08-29 20:25
Apologies, I had syncthing confused with btsync regarding the reverse proxy. Syncthing is indeed proxied via nginx; however, my point about syncthing not failing to install on my end remains true. A fresh install on a vultr vps, provided a working syncthing proxied through nginx.

As such, I cannot currently reproduce your issue and will require the debugging info I fleshed out for you above.

**Comment by Loomaanaatii** [comment] 2017-08-29 20:27
Sorry. It installs correctly. It just doesn't start.

**Comment by liaralabs** [comment] 2017-08-29 20:28
Since I cannot reproduce your issue, I require debugging info. Without this, I can do nothing.

**Comment by Loomaanaatii** [comment] 2017-08-30 23:49
`● syncthing@box.service - Syncthing - Open Source Continuous File Synchronization for box
   Loaded: loaded (/etc/systemd/system/syncthing@.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2017-08-31 01:47:38 CEST; 30s ago
     Docs: man:syncthing(1)
  Process: 11983 ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0 (code=exited, status=1/FAILURE)
 Main PID: 11983 (code=exited, status=1/FAILURE)

Aug 31 01:47:37 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Unit entered failed state.
Aug 31 01:47:37 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Failed with result 'exit-code'.
Aug 31 01:47:38 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Service hold-off time over, scheduling restart.
Aug 31 01:47:38 ns357103.ip-91-121-144.eu systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for box.
Aug 31 01:47:38 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Start request repeated too quickly.
Aug 31 01:47:38 ns357103.ip-91-121-144.eu systemd[1]: Failed to start Syncthing - Open Source Continuous File Synchronization for box.
`
`
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for box.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Unit entered failed state.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Failed with result 'exit-code'.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Service hold-off time over, scheduling restart.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for box.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Start request repeated too quickly.
Aug 29 05:16:05 ns357103.ip-91-121-144.eu systemd[1]: Failed to start Syncthing - Open Source Continuous File Synchronization for box.
Aug 29 05:16:45 ns357103.ip-91-121-144.eu systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for box.
Aug 29 05:16:45 ns357103.ip-91-121-144.eu systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for box.
Aug 29 05:16:45 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 05:16:45 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Unit entered failed state.
Aug 29 05:16:45 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Failed with result 'exit-code'.
Aug 29 05:16:46 ns357103.ip-91-121-144.eu systemd[1]: syncthing@box.service: Service hold-off time over, scheduling restart.
Aug 29 05:16:46 ns357103.ip-91-121-144.eu systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for box.
lines 1-40
`

**Comment by Loomaanaatii** [comment] 2017-09-03 02:58
@liaralabs Any updates?

**Comment by liaralabs** [comment] 2017-09-03 03:08
Did syncthing actually get installed?

`which syncthing`

You can try installing syncthing straight from apt

`sudo apt install syncthing`

It's pretty much a straight package install from apt-get there's not much that can go wrong.

**Comment by Loomaanaatii** [comment] 2017-09-03 03:11
> root@xxxxx:~# which syncthing
/usr/bin/syncthing
root@xxxxx:~# sudo apt install syncthing
Reading package lists... Done
Building dependency tree
Reading state information... Done
syncthing is already the newest version (0.14.36).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
root@xxxxx:~#

**Comment by liaralabs** [comment] 2017-09-03 03:14
Is there a conflicting syncthing process running? `systemctl status syncthing`

**Comment by liaralabs** [comment] 2017-09-03 03:16
The last thing I can recommend is to just run `syncthing` as your user to start the application in the foreground. Any errors should be printed.

**Comment by Loomaanaatii** [comment] 2017-09-03 03:17
So it worked running that command. Doesn't work when starting from the panel, though.

**Comment by liaralabs** [comment] 2017-09-03 03:18
What happens if you try `systemctl start syncthing@box`?

**Comment by Loomaanaatii** [comment] 2017-09-03 03:18
Nothing

**Comment by liaralabs** [comment] 2017-09-03 03:24
And `journalctl -u syncthing@box`? There may be a lot of output and this window can be scrolled with the arrow keys

**Comment by liaralabs** [comment] 2017-09-13 17:05
Closing because I cannot reproduce this issue and I haven't received enough information to fix this issue. If you would like to continue troubleshooting this issue and can supply me with the output of `journalctl -u syncthing@box`, please feel free to comment.

**Closed by liaralabs** 2017-09-13 17:05 UTC

**Comment by Energyboost** [comment] 2019-06-04 19:29
im having the extract same problem

**Comment by Energyboost** [comment] 2019-06-04 19:34
` systemctl status syncthing@boost.service
● syncthing@boost.service - Syncthing - Open Source Continuous File Synchronization for boost
   Loaded: loaded (/etc/systemd/system/syncthing@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-06-04 21:28:12 CEST; 2min 21s ago
     Docs: man:syncthing(1)
  Process: 21633 ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0 (code=exited, status=1/FAILURE)
 Main PID: 21633 (code=exited, status=1/FAILURE)
`

`journalctl -u syncthing.service
-- No entries --
`
`journalctl -u syncthing@boost.service
-- Logs begin at Tue 2019-06-04 20:53:35 CEST, end at Tue 2019-06-04 21:31:43 CEST. --
Jun 04 20:53:39 sd-117976 systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for boost.
Jun 04 20:53:48 sd-117976 systemd[1]: syncthing@boost.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 20:53:48 sd-117976 systemd[1]: syncthing@boost.service: Unit entered failed state.
Jun 04 20:53:48 sd-117976 systemd[1]: syncthing@boost.service: Failed with result 'exit-code'.
Jun 04 20:53:49 sd-117976 systemd[1]: syncthing@boost.service: Service hold-off time over, scheduling restart.
Jun 04 20:53:49 sd-117976 systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for boost.
Jun 04 20:53:49 sd-117976 systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for boost.
Jun 04 20:53:50 sd-117976 systemd[1]: syncthing@boost.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 20:53:50 sd-117976 systemd[1]: syncthing@boost.service: Unit entered failed state.
Jun 04 20:53:50 sd-117976 systemd[1]: syncthing@boost.service: Failed with result 'exit-code'.
`
`journalctl -u syncthing@box
-- No entries --
`
`syncthing
21:33:17 WARNING: Failure on home directory: mkdir /home/boost/.config/syncthing: permission denied
`
running as su in forground works fine

**Comment by liaralabs** [comment] 2019-06-04 19:49
The issue is here, in the last line you pasted:
```
 syncthing 21:33:17 WARNING: Failure on home directory: mkdir /home/boost/.config/syncthing: permission denied 
```
The permissions of /home/boost/.config/syncthing are incorrect (I'm guessing root owns the syncthing folder?)

You can view the permissions of the folder with `ls -la /home/boost/.config/`

Syncthing should be owned by the user `boost` and .config should also be owned.

You can change ownership of all the files and directories in you .config folder with `sudo chown -R boost: /home/boost/.config`

**Comment by Energyboost** [comment] 2019-06-04 19:52
lovely just the job thanks
