### ISSUE TITLE
Mariadb install error

### ISSUE THREAD

**Issue by cachenow** [liaralabs/swizzin#61] opened 2018-02-23 11:13 UTC
The progress show mariadb error messages:

Failed to start mariadb.service: Unit mariadb.service failed to load: No such file or directory.

and I set the nextCloud also show the error via Mariadb  : 
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'localhost' (using password: YES)

**Comment by liaralabs** [comment] 2018-02-23 19:12
Which OS? I will attempt to reproduce in a test environment.

If mariadb won't start, the rest of the errors are completely expected.

**Comment by cachenow** [comment] 2018-02-24 02:34
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

@liaralabs

**Comment by liaralabs** [comment] 2018-02-26 20:17
It looks like the version of MariaDB shipped with Jessie is pretty finicky regarding hosts assigned to users.

I have pushed some commits to the dev branch that should resolve this; however, if you want to get your install working, the following commands should do it:

First set your variables:
```
password=(enter your root mysql password here)
nextpass=(the password of your nextcloud database user)
```

Pass the commands:
```
mysql --user="root" --password="$password" --execute="DROP USER nextcloud@127.0.0.1;"
mysql --user="root" --password="$password" --execute="CREATE USER nextcloud@localhost IDENTIFIED BY '$nextpass';"
mysql --user="root" --password="$password" --execute="GRANT ALL PRIVILEGES ON nextcloud.* TO nextcloud@localhost;"
mysql --user="root" --password="$password" --execute="FLUSH PRIVILEGES;"
```

After creating the user nextcloud@localhost, you should now be able to complete the setup of nextcloud with the user nextcloud at host localhost.

**Comment by liaralabs** [comment] 2018-03-03 22:55
Changes have been pushed to master

**Closed by liaralabs** 2018-03-03 22:55 UTC
