### ISSUE TITLE
Emby

### ISSUE THREAD

**Issue by williamstorm1** [liaralabs/swizzin#110] opened 2018-05-26 12:47 UTC
no working update for emby, breaks the server - status: disabled and wont enable.

**Comment by liaralabs** [comment] 2018-05-31 17:48
The update process for emby is a bit variable depending on which OS you're on, but for most an apt upgrade should take care of the trick -- I also believe there are internal update mechanisms within emby server.

**Comment by liaralabs** [comment] 2018-06-17 22:48
I've been taking a bit of a look at this and I cannot reproduce in Debian.

Can you give me more info about this issue (OS, steps you are taking, etc)? Otherwise I will need to close it.

16.04/Debian 9 use the emby apt repository, so apt-get will keep your install up to date. 17.10 and 18.04 pull the release straight from github and install from there.

The upgrade script itself does the same (pulls from github) and is working despite not being needed on Debian 9.

**Comment by liaralabs** [comment] 2018-08-18 20:36
Closing as there has been no update an the issue is not reproducible. Please re-open if you are facing issues still.

**Closed by liaralabs** 2018-08-18 20:36 UTC
